version: "3.8"
services:
  master:
    image: master-node
    ports:
      - "5000:5000"
  worker1:
    image: worker-node
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
  worker2:
    image: worker-node
    ports:
      - "5002:5001"
    environment:
      - PORT=5002
