# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: image_processing.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'image_processing.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16image_processing.proto\"\"\n\x0cImageRequest\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\"9\n\rImageResponse\x12(\n\x10worker_responses\x18\x01 \x03(\x0b\x32\x0e.ChunkResponse\"\"\n\x0c\x43hunkRequest\x12\x12\n\nchunk_data\x18\x01 \x01(\x0c\"2\n\rChunkResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\x12\x11\n\tworker_id\x18\x02 \x01(\t2>\n\rMasterService\x12-\n\x0cProcessImage\x12\r.ImageRequest\x1a\x0e.ImageResponse2>\n\rWorkerService\x12-\n\x0cProcessChunk\x12\r.ChunkRequest\x1a\x0e.ChunkResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'image_processing_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGEREQUEST']._serialized_start=26
  _globals['_IMAGEREQUEST']._serialized_end=60
  _globals['_IMAGERESPONSE']._serialized_start=62
  _globals['_IMAGERESPONSE']._serialized_end=119
  _globals['_CHUNKREQUEST']._serialized_start=121
  _globals['_CHUNKREQUEST']._serialized_end=155
  _globals['_CHUNKRESPONSE']._serialized_start=157
  _globals['_CHUNKRESPONSE']._serialized_end=207
  _globals['_MASTERSERVICE']._serialized_start=209
  _globals['_MASTERSERVICE']._serialized_end=271
  _globals['_WORKERSERVICE']._serialized_start=273
  _globals['_WORKERSERVICE']._serialized_end=335
# @@protoc_insertion_point(module_scope)
