# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: image_processing.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'image_processing.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16image_processing.proto\"\"\n\x0cImageRequest\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\"#\n\rImageResponse\x12\x12\n\nrequest_id\x18\x01 \x01(\t\"\"\n\x0cQueryRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\"0\n\x0eResultResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0e\n\x06result\x18\x02 \x01(\t\"\x0e\n\x0cModelRequest\"F\n\tModelInfo\x12\x12\n\nmodel_name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x10\n\x08\x61\x63\x63uracy\x18\x03 \x01(\x01\"(\n\x12ModelDetailRequest\x12\x12\n\nmodel_name\x18\x01 \x01(\t\"H\n\x0bModelDetail\x12\x12\n\nmodel_name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x10\n\x08\x61\x63\x63uracy\x18\x03 \x01(\x01\"\"\n\x0c\x43hunkRequest\x12\x12\n\nchunk_data\x18\x01 \x01(\x0c\"2\n\rChunkResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\x12\x11\n\tworker_id\x18\x02 \x01(\t\"\x0f\n\rHealthRequest\" \n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\xcd\x01\n\rMasterService\x12-\n\x0cProcessImage\x12\r.ImageRequest\x1a\x0e.ImageResponse\x12-\n\x0bQueryResult\x12\r.QueryRequest\x1a\x0f.ResultResponse\x12(\n\tGetModels\x12\r.ModelRequest\x1a\n.ModelInfo0\x01\x12\x34\n\x0fGetModelDetails\x12\x13.ModelDetailRequest\x1a\x0c.ModelDetail2n\n\rWorkerService\x12-\n\x0cProcessChunk\x12\r.ChunkRequest\x1a\x0e.ChunkResponse\x12.\n\x0bHealthCheck\x12\x0e.HealthRequest\x1a\x0f.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'image_processing_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGEREQUEST']._serialized_start=26
  _globals['_IMAGEREQUEST']._serialized_end=60
  _globals['_IMAGERESPONSE']._serialized_start=62
  _globals['_IMAGERESPONSE']._serialized_end=97
  _globals['_QUERYREQUEST']._serialized_start=99
  _globals['_QUERYREQUEST']._serialized_end=133
  _globals['_RESULTRESPONSE']._serialized_start=135
  _globals['_RESULTRESPONSE']._serialized_end=183
  _globals['_MODELREQUEST']._serialized_start=185
  _globals['_MODELREQUEST']._serialized_end=199
  _globals['_MODELINFO']._serialized_start=201
  _globals['_MODELINFO']._serialized_end=271
  _globals['_MODELDETAILREQUEST']._serialized_start=273
  _globals['_MODELDETAILREQUEST']._serialized_end=313
  _globals['_MODELDETAIL']._serialized_start=315
  _globals['_MODELDETAIL']._serialized_end=387
  _globals['_CHUNKREQUEST']._serialized_start=389
  _globals['_CHUNKREQUEST']._serialized_end=423
  _globals['_CHUNKRESPONSE']._serialized_start=425
  _globals['_CHUNKRESPONSE']._serialized_end=475
  _globals['_HEALTHREQUEST']._serialized_start=477
  _globals['_HEALTHREQUEST']._serialized_end=492
  _globals['_HEALTHRESPONSE']._serialized_start=494
  _globals['_HEALTHRESPONSE']._serialized_end=526
  _globals['_MASTERSERVICE']._serialized_start=529
  _globals['_MASTERSERVICE']._serialized_end=734
  _globals['_WORKERSERVICE']._serialized_start=736
  _globals['_WORKERSERVICE']._serialized_end=846
# @@protoc_insertion_point(module_scope)
