# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import image_processing_pb2 as image__processing__pb2

GRPC_GENERATED_VERSION = '1.68.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in image_processing_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MasterServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessImage = channel.unary_unary(
                '/MasterService/ProcessImage',
                request_serializer=image__processing__pb2.ImageRequest.SerializeToString,
                response_deserializer=image__processing__pb2.ImageResponse.FromString,
                _registered_method=True)
        self.QueryResult = channel.unary_unary(
                '/MasterService/QueryResult',
                request_serializer=image__processing__pb2.ResultRequest.SerializeToString,
                response_deserializer=image__processing__pb2.ResultResponse.FromString,
                _registered_method=True)
        self.GetModels = channel.unary_unary(
                '/MasterService/GetModels',
                request_serializer=image__processing__pb2.ModelRequest.SerializeToString,
                response_deserializer=image__processing__pb2.ModelResponse.FromString,
                _registered_method=True)
        self.GetModelDetails = channel.unary_unary(
                '/MasterService/GetModelDetails',
                request_serializer=image__processing__pb2.ModelDetailRequest.SerializeToString,
                response_deserializer=image__processing__pb2.ModelDetailResponse.FromString,
                _registered_method=True)


class MasterServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ProcessImage(self, request, context):
        """Existing
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryResult(self, request, context):
        """Fetch results
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModels(self, request, context):
        """List models
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModelDetails(self, request, context):
        """Model details
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MasterServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessImage': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessImage,
                    request_deserializer=image__processing__pb2.ImageRequest.FromString,
                    response_serializer=image__processing__pb2.ImageResponse.SerializeToString,
            ),
            'QueryResult': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryResult,
                    request_deserializer=image__processing__pb2.ResultRequest.FromString,
                    response_serializer=image__processing__pb2.ResultResponse.SerializeToString,
            ),
            'GetModels': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModels,
                    request_deserializer=image__processing__pb2.ModelRequest.FromString,
                    response_serializer=image__processing__pb2.ModelResponse.SerializeToString,
            ),
            'GetModelDetails': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModelDetails,
                    request_deserializer=image__processing__pb2.ModelDetailRequest.FromString,
                    response_serializer=image__processing__pb2.ModelDetailResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'MasterService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('MasterService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MasterService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ProcessImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MasterService/ProcessImage',
            image__processing__pb2.ImageRequest.SerializeToString,
            image__processing__pb2.ImageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MasterService/QueryResult',
            image__processing__pb2.ResultRequest.SerializeToString,
            image__processing__pb2.ResultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MasterService/GetModels',
            image__processing__pb2.ModelRequest.SerializeToString,
            image__processing__pb2.ModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetModelDetails(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MasterService/GetModelDetails',
            image__processing__pb2.ModelDetailRequest.SerializeToString,
            image__processing__pb2.ModelDetailResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
